#!/usr/bin/env bash
set -Eeu -o pipefail

psql --dbname="$POSTGRES_DB" --user="$POSTGRES_USER" << EOF
CREATE USER ${DATABASE_DEVELOPER_USER?DATABASE_DEVELOPER_USER is required} 
	WITH LOGIN NOCREATEDB NOCREATEROLE NOBYPASSRLS
	PASSWORD '${DATABASE_DEVELOPER_PASS?DATABASE_DEVELOPER_PASS is required}';

ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT ALL PRIVILEGES ON TABLES TO ${DATABASE_DEVELOPER_USER};

GRANT USAGE ON SCHEMA public TO ${DATABASE_DEVELOPER_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT USAGE, UPDATE, SELECT ON SEQUENCES TO ${DATABASE_DEVELOPER_USER};
EOF

container-migrations-manage apply
