FROM golang:1.25.6-alpine3.23 AS builder

WORKDIR /chat

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./src/ ./src/

RUN go build -o /usr/local/bin/chat ./src/

FROM alpine:3.23

COPY --from=builder /usr/local/bin/chat /usr/local/bin/chat

EXPOSE 3003

ENTRYPOINT [ "chat" ]
