FROM golang:1.25-alpine3.23 AS builder

RUN apk add --no-cache \
	gpgme-dev btrfs-progs-dev gcc musl-dev

WORKDIR /app
COPY go.mod go.sum app.go env.go main.go routes.go stream.go tar.go ./

RUN mkdir podman/
COPY ./podman/go.mod ./podman/go.sum ./podman/podman.go ./podman/containers.go ./podman/images.go ./podman/

RUN go mod tidy && go mod download
RUN go build -o sandbox .

FROM alpine:3.23 AS runner

RUN apk add --no-cache \
	gpgme btrfs-progs

WORKDIR /app
COPY --from=builder /app/sandbox .

EXPOSE 3006
ENTRYPOINT [ "./sandbox" ]
