FROM docker.io/library/golang:1.25.6-alpine3.23 AS builder

RUN apk add --no-cache \
    gpgme-dev \
    btrfs-progs-dev \
    gcc \
    musl-dev 

WORKDIR /usr/src/app
COPY    go.mod go.sum .
RUN     go mod download

COPY    . .
RUN     go build -o /usr/local/bin/app-sandbox .

FROM alpine:3.23

RUN apk add --no-cache gpgme btrfs-progs

COPY --from=builder /usr/local/bin/app-sandbox /usr/local/bin/app-sandbox

ENTRYPOINT [ "app-sandbox" ]
