ALTER TABLE ctfs ADD COLUMN name TEXT NOT NULL DEFAULT 'New Event';
ALTER TABLE ctfs ADD COLUMN start_time TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE ctfs ADD COLUMN start_time TIMESTAMP NOT NULL DEFAULT (NOW() + interval '24 hours');