FROM node:24.12-alpine3.23 AS builder

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml* ./

RUN pnpm install --frozen-lockfile

COPY tsconfig.json vite.config.ts react-router.config.ts ./
COPY app ./app
COPY public ./public

ARG BROWSER_REST_USER_ORIGIN
ENV BROWSER_REST_USER_ORIGIN=$BROWSER_REST_USER_ORIGIN


ARG BROWSER_SOCKET_NOTIFICATION
ENV BROWSER_SOCKET_NOTIFICATION=$BROWSER_SOCKET_NOTIFICATION

RUN pnpm run build

# Production stage
FROM node:24.12-alpine3.23

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml* ./

RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/build ./build

EXPOSE 3000

CMD ["pnpm", "run", "start"]