FROM docker.io/library/golang:1.25

WORKDIR /usr/src/myapp

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /usr/local/bin/notification .

EXPOSE 3004

ENTRYPOINT ["notification"]